spring:
  cloud:
    gateway:
      routes:
        - id: file
          uri: lb://wy-file
          predicates:
            - Path=/api/wy-file/**
          filters:
            - StripPrefix=2
        - id: authentication
          uri: lb://wy-authentication
          predicates:
            - Path=/api/wy-authentication/**
          filters:
            - StripPrefix=2
        - id: organizaiton
          uri: lb://wy-organization
          predicates:
            - Path=/api/wy-organization/**
          filters:
            - StripPrefix=2

