spring:
  cloud:
    gateway:
      routes:
        - id: aggregation
          uri: lb://wy-aggregation
          predicates:
            - Path=/api/**
            - name: Aggregation
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            - StripPrefix=2